### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Review by alexAubin — COMMENTED** [review]
I'm thinking the CI reports a 502 error after install propably because nowadays rspamd is stopped/disabled by default to save up RAM ... Maybe we can add some `systemctl enable rspamd --now` in the pre-install section of check_process / tests.toml

**Comment by alexAubin** [comment]
!testme

**Comment by alexAubin** [comment]
Hmpf, better but not perfect ... but let's yolo merge to at least move on a bit with this, the PR is already like 6 months old

**Pull request merged**
